// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  cat_img: string;
  content: string;
  error: string;
}
export const cssExports: CssExports;
export default cssExports;
